# Generated by Django 3.2.14 on 2022-07-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='user_id',
            new_name='m_user_id',
        ),
    ]
